on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - uses: actions/checkout@v4

      # Set up JDK (Java Development Kit) for Android build
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          build-tools: 30.0.3

      # Accept licenses
      - name: Accept Android SDK licenses
        run: yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses

      # Build the Android app
      - name: Build Android App with Gradle
        run: ./gradlew build

      # (Optional) Run tests
      - name: Run Android Tests
        run: ./gradlew test
